name: tdlib_ex
description: A Dart wrapper and client for Telegram TDLib (tdjson) with generated API classes.
version: 0.40.0
repository: https://github.com/sla-000/tdlib-dart

environment:
  sdk: '>=2.16.0 <4.0.0'

dependencies:
  collection: ^1.0.0
  ffi: ^2.0.0
  meta: ^1.0.0
  rxdart: '>=0.26.0 <1.0.0'