// ignore: unused_import
import 'package:collection/collection.dart';
import 'package:meta/meta.dart';
import '../tdapi.dart';

/// Contains the content of a message
@immutable
abstract class MessageContent extends TdObject {
  const MessageContent();

  static const String constructor = 'messageContent';

  /// Inherited by:
  /// [MessageAnimatedEmoji]
  /// [MessageAnimation]
  /// [MessageAudio]
  /// [MessageBasicGroupChatCreate]
  /// [MessageBotWriteAccessAllowed]
  /// [MessageCall]
  /// [MessageChatAddMembers]
  /// [MessageChatAddedToCommunity]
  /// [MessageChatBoost]
  /// [MessageChatChangePhoto]
  /// [MessageChatChangeTitle]
  /// [MessageChatDeleteMember]
  /// [MessageChatDeletePhoto]
  /// [MessageChatHasProtectedContentDisableRequested]
  /// [MessageChatHasProtectedContentToggled]
  /// [MessageChatJoinByLink]
  /// [MessageChatJoinByRequest]
  /// [MessageChatJoinFromCommunity]
  /// [MessageChatOwnerChanged]
  /// [MessageChatOwnerLeft]
  /// [MessageChatRemovedFromCommunity]
  /// [MessageChatSetBackground]
  /// [MessageChatSetMessageAutoDeleteTime]
  /// [MessageChatSetTheme]
  /// [MessageChatShared]
  /// [MessageChatUpgradeFrom]
  /// [MessageChatUpgradeTo]
  /// [MessageChecklistTasksAdded]
  /// [MessageChecklistTasksDone]
  /// [MessageChecklist]
  /// [MessageContactRegistered]
  /// [MessageContact]
  /// [MessageCustomServiceAction]
  /// [MessageDice]
  /// [MessageDirectMessagePriceChanged]
  /// [MessageDocument]
  /// [MessageExpiredPhoto]
  /// [MessageExpiredVideoNote]
  /// [MessageExpiredVideo]
  /// [MessageExpiredVoiceNote]
  /// [MessageForumTopicCreated]
  /// [MessageForumTopicEdited]
  /// [MessageForumTopicIsClosedToggled]
  /// [MessageForumTopicIsHiddenToggled]
  /// [MessageGameScore]
  /// [MessageGame]
  /// [MessageGift]
  /// [MessageGiftedGrams]
  /// [MessageGiftedPremium]
  /// [MessageGiftedStars]
  /// [MessageGiveawayCompleted]
  /// [MessageGiveawayCreated]
  /// [MessageGiveawayPrizeStars]
  /// [MessageGiveawayWinners]
  /// [MessageGiveaway]
  /// [MessageGroupCall]
  /// [MessageInviteVideoChatParticipants]
  /// [MessageInvoice]
  /// [MessageLiveLocation]
  /// [MessageLocation]
  /// [MessageManagedBotCreated]
  /// [MessagePaidMedia]
  /// [MessagePaidMessagePriceChanged]
  /// [MessagePaidMessagesRefunded]
  /// [MessagePassportDataReceived]
  /// [MessagePassportDataSent]
  /// [MessagePaymentRefunded]
  /// [MessagePaymentSuccessfulBot]
  /// [MessagePaymentSuccessful]
  /// [MessagePhoto]
  /// [MessagePinMessage]
  /// [MessagePollOptionAdded]
  /// [MessagePollOptionDeleted]
  /// [MessagePoll]
  /// [MessagePremiumGiftCode]
  /// [MessageProximityAlertTriggered]
  /// [MessageRefundedUpgradedGift]
  /// [MessageRichMessage]
  /// [MessageScreenshotTaken]
  /// [MessageStakeDice]
  /// [MessageSticker]
  /// [MessageStory]
  /// [MessageSuggestBirthdate]
  /// [MessageSuggestProfilePhoto]
  /// [MessageSuggestedPostApprovalFailed]
  /// [MessageSuggestedPostApproved]
  /// [MessageSuggestedPostDeclined]
  /// [MessageSuggestedPostPaid]
  /// [MessageSuggestedPostRefunded]
  /// [MessageSupergroupChatCreate]
  /// [MessageText]
  /// [MessageUnsupported]
  /// [MessageUpgradedGiftPurchaseOfferRejected]
  /// [MessageUpgradedGiftPurchaseOffer]
  /// [MessageUpgradedGift]
  /// [MessageUsersShared]
  /// [MessageVenue]
  /// [MessageVideoChatEnded]
  /// [MessageVideoChatScheduled]
  /// [MessageVideoChatStarted]
  /// [MessageVideoNote]
  /// [MessageVideo]
  /// [MessageVoiceNote]
  /// [MessageWebAppDataReceived]
  /// [MessageWebAppDataSent]
  static MessageContent? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    switch (json['@type']) {
      case MessageAnimatedEmoji.constructor:
        return MessageAnimatedEmoji.fromJson(json);
      case MessageAnimation.constructor:
        return MessageAnimation.fromJson(json);
      case MessageAudio.constructor:
        return MessageAudio.fromJson(json);
      case MessageBasicGroupChatCreate.constructor:
        return MessageBasicGroupChatCreate.fromJson(json);
      case MessageBotWriteAccessAllowed.constructor:
        return MessageBotWriteAccessAllowed.fromJson(json);
      case MessageCall.constructor:
        return MessageCall.fromJson(json);
      case MessageChatAddMembers.constructor:
        return MessageChatAddMembers.fromJson(json);
      case MessageChatAddedToCommunity.constructor:
        return MessageChatAddedToCommunity.fromJson(json);
      case MessageChatBoost.constructor:
        return MessageChatBoost.fromJson(json);
      case MessageChatChangePhoto.constructor:
        return MessageChatChangePhoto.fromJson(json);
      case MessageChatChangeTitle.constructor:
        return MessageChatChangeTitle.fromJson(json);
      case MessageChatDeleteMember.constructor:
        return MessageChatDeleteMember.fromJson(json);
      case MessageChatDeletePhoto.constructor:
        return MessageChatDeletePhoto.fromJson(json);
      case MessageChatHasProtectedContentDisableRequested.constructor:
        return MessageChatHasProtectedContentDisableRequested.fromJson(json);
      case MessageChatHasProtectedContentToggled.constructor:
        return MessageChatHasProtectedContentToggled.fromJson(json);
      case MessageChatJoinByLink.constructor:
        return MessageChatJoinByLink.fromJson(json);
      case MessageChatJoinByRequest.constructor:
        return MessageChatJoinByRequest.fromJson(json);
      case MessageChatJoinFromCommunity.constructor:
        return MessageChatJoinFromCommunity.fromJson(json);
      case MessageChatOwnerChanged.constructor:
        return MessageChatOwnerChanged.fromJson(json);
      case MessageChatOwnerLeft.constructor:
        return MessageChatOwnerLeft.fromJson(json);
      case MessageChatRemovedFromCommunity.constructor:
        return MessageChatRemovedFromCommunity.fromJson(json);
      case MessageChatSetBackground.constructor:
        return MessageChatSetBackground.fromJson(json);
      case MessageChatSetMessageAutoDeleteTime.constructor:
        return MessageChatSetMessageAutoDeleteTime.fromJson(json);
      case MessageChatSetTheme.constructor:
        return MessageChatSetTheme.fromJson(json);
      case MessageChatShared.constructor:
        return MessageChatShared.fromJson(json);
      case MessageChatUpgradeFrom.constructor:
        return MessageChatUpgradeFrom.fromJson(json);
      case MessageChatUpgradeTo.constructor:
        return MessageChatUpgradeTo.fromJson(json);
      case MessageChecklist.constructor:
        return MessageChecklist.fromJson(json);
      case MessageChecklistTasksAdded.constructor:
        return MessageChecklistTasksAdded.fromJson(json);
      case MessageChecklistTasksDone.constructor:
        return MessageChecklistTasksDone.fromJson(json);
      case MessageContact.constructor:
        return MessageContact.fromJson(json);
      case MessageContactRegistered.constructor:
        return MessageContactRegistered.fromJson(json);
      case MessageCustomServiceAction.constructor:
        return MessageCustomServiceAction.fromJson(json);
      case MessageDice.constructor:
        return MessageDice.fromJson(json);
      case MessageDirectMessagePriceChanged.constructor:
        return MessageDirectMessagePriceChanged.fromJson(json);
      case MessageDocument.constructor:
        return MessageDocument.fromJson(json);
      case MessageExpiredPhoto.constructor:
        return MessageExpiredPhoto.fromJson(json);
      case MessageExpiredVideo.constructor:
        return MessageExpiredVideo.fromJson(json);
      case MessageExpiredVideoNote.constructor:
        return MessageExpiredVideoNote.fromJson(json);
      case MessageExpiredVoiceNote.constructor:
        return MessageExpiredVoiceNote.fromJson(json);
      case MessageForumTopicCreated.constructor:
        return MessageForumTopicCreated.fromJson(json);
      case MessageForumTopicEdited.constructor:
        return MessageForumTopicEdited.fromJson(json);
      case MessageForumTopicIsClosedToggled.constructor:
        return MessageForumTopicIsClosedToggled.fromJson(json);
      case MessageForumTopicIsHiddenToggled.constructor:
        return MessageForumTopicIsHiddenToggled.fromJson(json);
      case MessageGame.constructor:
        return MessageGame.fromJson(json);
      case MessageGameScore.constructor:
        return MessageGameScore.fromJson(json);
      case MessageGift.constructor:
        return MessageGift.fromJson(json);
      case MessageGiftedGrams.constructor:
        return MessageGiftedGrams.fromJson(json);
      case MessageGiftedPremium.constructor:
        return MessageGiftedPremium.fromJson(json);
      case MessageGiftedStars.constructor:
        return MessageGiftedStars.fromJson(json);
      case MessageGiveaway.constructor:
        return MessageGiveaway.fromJson(json);
      case MessageGiveawayCompleted.constructor:
        return MessageGiveawayCompleted.fromJson(json);
      case MessageGiveawayCreated.constructor:
        return MessageGiveawayCreated.fromJson(json);
      case MessageGiveawayPrizeStars.constructor:
        return MessageGiveawayPrizeStars.fromJson(json);
      case MessageGiveawayWinners.constructor:
        return MessageGiveawayWinners.fromJson(json);
      case MessageGroupCall.constructor:
        return MessageGroupCall.fromJson(json);
      case MessageInviteVideoChatParticipants.constructor:
        return MessageInviteVideoChatParticipants.fromJson(json);
      case MessageInvoice.constructor:
        return MessageInvoice.fromJson(json);
      case MessageLiveLocation.constructor:
        return MessageLiveLocation.fromJson(json);
      case MessageLocation.constructor:
        return MessageLocation.fromJson(json);
      case MessageManagedBotCreated.constructor:
        return MessageManagedBotCreated.fromJson(json);
      case MessagePaidMedia.constructor:
        return MessagePaidMedia.fromJson(json);
      case MessagePaidMessagePriceChanged.constructor:
        return MessagePaidMessagePriceChanged.fromJson(json);
      case MessagePaidMessagesRefunded.constructor:
        return MessagePaidMessagesRefunded.fromJson(json);
      case MessagePassportDataReceived.constructor:
        return MessagePassportDataReceived.fromJson(json);
      case MessagePassportDataSent.constructor:
        return MessagePassportDataSent.fromJson(json);
      case MessagePaymentRefunded.constructor:
        return MessagePaymentRefunded.fromJson(json);
      case MessagePaymentSuccessful.constructor:
        return MessagePaymentSuccessful.fromJson(json);
      case MessagePaymentSuccessfulBot.constructor:
        return MessagePaymentSuccessfulBot.fromJson(json);
      case MessagePhoto.constructor:
        return MessagePhoto.fromJson(json);
      case MessagePinMessage.constructor:
        return MessagePinMessage.fromJson(json);
      case MessagePoll.constructor:
        return MessagePoll.fromJson(json);
      case MessagePollOptionAdded.constructor:
        return MessagePollOptionAdded.fromJson(json);
      case MessagePollOptionDeleted.constructor:
        return MessagePollOptionDeleted.fromJson(json);
      case MessagePremiumGiftCode.constructor:
        return MessagePremiumGiftCode.fromJson(json);
      case MessageProximityAlertTriggered.constructor:
        return MessageProximityAlertTriggered.fromJson(json);
      case MessageRefundedUpgradedGift.constructor:
        return MessageRefundedUpgradedGift.fromJson(json);
      case MessageRichMessage.constructor:
        return MessageRichMessage.fromJson(json);
      case MessageScreenshotTaken.constructor:
        return MessageScreenshotTaken.fromJson(json);
      case MessageStakeDice.constructor:
        return MessageStakeDice.fromJson(json);
      case MessageSticker.constructor:
        return MessageSticker.fromJson(json);
      case MessageStory.constructor:
        return MessageStory.fromJson(json);
      case MessageSuggestBirthdate.constructor:
        return MessageSuggestBirthdate.fromJson(json);
      case MessageSuggestProfilePhoto.constructor:
        return MessageSuggestProfilePhoto.fromJson(json);
      case MessageSuggestedPostApprovalFailed.constructor:
        return MessageSuggestedPostApprovalFailed.fromJson(json);
      case MessageSuggestedPostApproved.constructor:
        return MessageSuggestedPostApproved.fromJson(json);
      case MessageSuggestedPostDeclined.constructor:
        return MessageSuggestedPostDeclined.fromJson(json);
      case MessageSuggestedPostPaid.constructor:
        return MessageSuggestedPostPaid.fromJson(json);
      case MessageSuggestedPostRefunded.constructor:
        return MessageSuggestedPostRefunded.fromJson(json);
      case MessageSupergroupChatCreate.constructor:
        return MessageSupergroupChatCreate.fromJson(json);
      case MessageText.constructor:
        return MessageText.fromJson(json);
      case MessageUnsupported.constructor:
        return MessageUnsupported.fromJson(json);
      case MessageUpgradedGift.constructor:
        return MessageUpgradedGift.fromJson(json);
      case MessageUpgradedGiftPurchaseOffer.constructor:
        return MessageUpgradedGiftPurchaseOffer.fromJson(json);
      case MessageUpgradedGiftPurchaseOfferRejected.constructor:
        return MessageUpgradedGiftPurchaseOfferRejected.fromJson(json);
      case MessageUsersShared.constructor:
        return MessageUsersShared.fromJson(json);
      case MessageVenue.constructor:
        return MessageVenue.fromJson(json);
      case MessageVideo.constructor:
        return MessageVideo.fromJson(json);
      case MessageVideoChatEnded.constructor:
        return MessageVideoChatEnded.fromJson(json);
      case MessageVideoChatScheduled.constructor:
        return MessageVideoChatScheduled.fromJson(json);
      case MessageVideoChatStarted.constructor:
        return MessageVideoChatStarted.fromJson(json);
      case MessageVideoNote.constructor:
        return MessageVideoNote.fromJson(json);
      case MessageVoiceNote.constructor:
        return MessageVoiceNote.fromJson(json);
      case MessageWebAppDataReceived.constructor:
        return MessageWebAppDataReceived.fromJson(json);
      case MessageWebAppDataSent.constructor:
        return MessageWebAppDataSent.fromJson(json);
      default:
        return null;
    }
  }

  @override
  String getConstructor() => constructor;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other.runtimeType == runtimeType && other is MessageContent);

  @override
  int get hashCode => runtimeType.hashCode;
}
