// ignore: unused_import
import 'package:collection/collection.dart';
import 'package:meta/meta.dart';
import '../tdapi.dart';

/// A stake dice message. The dice value is randomly generated by the server
@immutable
class MessageStakeDice extends MessageContent {
  const MessageStakeDice({
    this.initialState,
    this.finalState,
    required this.value,
    required this.stakeToncoinAmount,
    required this.prizeToncoinAmount,
  });

  /// [initialState] The animated stickers with the initial dice animation; may
  /// be null if unknown. The update updateMessageContent will be sent when the
  /// sticker became known
  final DiceStickers? initialState;

  /// [finalState] The animated stickers with the final dice animation; may be
  /// null if unknown. The update updateMessageContent will be sent when the
  /// sticker became known
  final DiceStickers? finalState;

  /// [value] The dice value. If the value is 0, then the dice don't have final
  /// state yet
  final int value;

  /// [stakeToncoinAmount] The Toncoin amount that was staked; in the smallest
  /// units of the currency
  final int stakeToncoinAmount;

  /// [prizeToncoinAmount] The Toncoin amount that was gained from the roll; in
  /// the smallest units of the currency; -1 if the dice don't have final state
  /// yet
  final int prizeToncoinAmount;

  static const String constructor = 'messageStakeDice';

  static MessageStakeDice? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return MessageStakeDice(
      initialState:
          DiceStickers.fromJson(json['initial_state'] as Map<String, dynamic>?),
      finalState:
          DiceStickers.fromJson(json['final_state'] as Map<String, dynamic>?),
      value: json['value'] as int,
      stakeToncoinAmount: json['stake_toncoin_amount'] as int,
      prizeToncoinAmount: json['prize_toncoin_amount'] as int,
    );
  }

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
        'initial_state': initialState?.toJson(),
        'final_state': finalState?.toJson(),
        'value': value,
        'stake_toncoin_amount': stakeToncoinAmount,
        'prize_toncoin_amount': prizeToncoinAmount,
        '@type': constructor,
      };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other.runtimeType == runtimeType &&
          other is MessageStakeDice &&
          const DeepCollectionEquality()
              .equals(other.initialState, initialState) &&
          const DeepCollectionEquality().equals(other.finalState, finalState) &&
          const DeepCollectionEquality().equals(other.value, value) &&
          const DeepCollectionEquality()
              .equals(other.stakeToncoinAmount, stakeToncoinAmount) &&
          const DeepCollectionEquality()
              .equals(other.prizeToncoinAmount, prizeToncoinAmount));

  @override
  int get hashCode => Object.hashAll([
        runtimeType,
        const DeepCollectionEquality().hash(initialState),
        const DeepCollectionEquality().hash(finalState),
        const DeepCollectionEquality().hash(value),
        const DeepCollectionEquality().hash(stakeToncoinAmount),
        const DeepCollectionEquality().hash(prizeToncoinAmount)
      ]);
}
