// ignore: unused_import
import 'package:collection/collection.dart';
import 'package:meta/meta.dart';
import '../tdapi.dart';

/// The file generation process needs to be started by the application. Use
/// setFileGenerationProgress and finishFileGeneration to generate the file
@immutable
class UpdateFileGenerationStart extends Update {
  const UpdateFileGenerationStart({
    required this.generationId,
    required this.originalPath,
    required this.destinationPath,
    required this.conversion,
  });

  /// [generationId] Unique identifier for the generation process
  final int generationId;

  /// [originalPath] The original path specified by the application in
  /// inputFileGenerated
  final String originalPath;

  /// [destinationPath] The path to a file that must be created and where the
  /// new file must be generated by the application. If the application has no
  /// access to the path, it can use writeGeneratedFilePart to generate the file
  final String destinationPath;

  /// [conversion] If the conversion is "#url#", then original_path contains an
  /// HTTP/HTTPS URL of a file that must be downloaded by the application.
  /// Otherwise, this is the conversion specified by the application in
  /// inputFileGenerated
  final String conversion;

  static const String constructor = 'updateFileGenerationStart';

  static UpdateFileGenerationStart? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return UpdateFileGenerationStart(
      generationId: (json['generation_id'] is int
              ? json['generation_id'] as int
              : int.tryParse(json['generation_id']?.toString() ?? '')) ??
          0,
      originalPath: (json['original_path'] as String?) ?? '',
      destinationPath: (json['destination_path'] as String?) ?? '',
      conversion: (json['conversion'] as String?) ?? '',
    );
  }

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
        'generation_id': generationId.toString(),
        'original_path': originalPath,
        'destination_path': destinationPath,
        'conversion': conversion,
        '@type': constructor,
      };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other.runtimeType == runtimeType &&
          other is UpdateFileGenerationStart &&
          const DeepCollectionEquality()
              .equals(other.generationId, generationId) &&
          const DeepCollectionEquality()
              .equals(other.originalPath, originalPath) &&
          const DeepCollectionEquality()
              .equals(other.destinationPath, destinationPath) &&
          const DeepCollectionEquality().equals(other.conversion, conversion));

  @override
  int get hashCode => Object.hashAll([
        runtimeType,
        const DeepCollectionEquality().hash(generationId),
        const DeepCollectionEquality().hash(originalPath),
        const DeepCollectionEquality().hash(destinationPath),
        const DeepCollectionEquality().hash(conversion)
      ]);
}
